#!/bin/sh
MyCommand=${0##*"/"}
CDir=${0%%/"$MyCommand"}
ScriptDir=$(cd $CDir && pwd)
ScriptCommand=SAP.py
if [ -f "$ScriptDir/SAP.pyc" ]
then
	ScriptCommand=SAP.pyc
fi

Version=0.70

python --version

if [ "$?" != "0" ]
then
	sudo apt-get install python
fi

clear

echo """
                         ###     StudioAndroid      ###
                         ###     GTK GUI Build      ###
                                      v$Version

"""

python $ScriptDir/$ScriptCommand

True=$( grep -w 'FirstRun = True' $ScriptDir/SAP.py )


if [ "$?" = "0" ] && [ "$True" != "" ]
then
	sed -i 's/FirstRun = True/FirstRun = False/g' $ScriptDir/SAP.py
	rm  -f $ScriptDir/SAP.pyc
fi



