#!/bin/sh
MyCommand=${0##*"/"}
CDir=${0%%/"$MyCommand"}
ScriptDir=$(cd $CDir && pwd)
ScriptCommand=SAP.py
if [ -f "$ScriptDir/SAP.pyc" ]
then
	ScriptCommand=SAP.pyc
fi


python --version

if [ "$?" != "0" ]
then
	sudo apt-get install python
fi

clear

python $ScriptDir/$ScriptCommand



