#!/bin/sh
MyCommand=${0##*"/"}
CDir=${0%%/"$MyCommand"}
ScriptDir=$(cd $CDir && pwd)
ScriptCommand=SA.py
if [ -f "$ScriptDir/SA.pyc" ]
then
	ScriptCommand=SA.pyc
fi


python --version

if [ "$?" != "0" ]
then
	sudo apt-get install python
fi

clear

python $ScriptDir/$ScriptCommand



